In [1]:
import pandas as pd

In [2]:
df_1 = pd.read_csv("Fortune_10.csv")

In [3]:
df_1

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [4]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv")

In [5]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [6]:
pd.__version__

'2.3.3'

# list

# Series

In [7]:
#scalar series

scalar_s = pd.Series(1)
print(scalar_s)

0    1
dtype: int64

In [8]:
scalar_s1 = pd.Series(0.2, index = [1,2,3,4])
print(scalar_s1)

1    0.2
2    0.2
3    0.2
4    0.2
dtype: float64

# Empty series

In [9]:
empty_s = pd.Series([])

type(empty_s)

empty_s

Series([], dtype: object)

# list to Series

In [10]:
list_s = [1,2,-5,3.0,'data']
print(list_s)
type(list_s)

[1, 2, -5, 3.0, 'data']

list

In [11]:
series = pd.Series(list_s)
print(series)

0       1
1       2
2      -5
3     3.0
4    data
dtype: object

In [12]:
type(series)

pandas.core.series.Series

# dictionary to Series

In [13]:
dict_s = pd.Series({'a' : 1 , 'b': 2})
dict_s

a    1
b    2
dtype: int64

In [14]:
dict2 = {'ID' : [1,2,3,4],
        "name": ['raja', 'rani', 'varsova','rajkot']}
dict2

{'ID': [1, 2, 3, 4], 'name': ['raja', 'rani', 'varsova', 'rajkot']}

In [15]:
df_dict_s = pd.Series(dict2)
df_dict_s

ID                       [1, 2, 3, 4]
name    [raja, rani, varsova, rajkot]
dtype: object

In [16]:
series_1 = pd.Series([2,3,4,5], index = ['a','b','c','d'])
print(series_1)

a    2
b    3
c    4
d    5
dtype: int64

In [17]:
#chaging data type

series_2 = pd.Series([1,2,3,4], index = ['o','k','o','k'], dtype = float, name = 'data')
print(series_2)

# 'name' parameter

o    1.0
k    2.0
o    3.0
k    4.0
Name: data, dtype: float64

# indexing in series

In [18]:
sr_indx = pd.Series([1,2,3,4,5])
print(sr_indx)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
sr_indx[0]

np.int64(1)

In [20]:
sr_indx[1]

np.int64(2)

In [21]:
sr_indx[0:4]

0    1
1    2
2    3
3    4
dtype: int64

In [22]:
min(sr_indx)

1

In [23]:
max(sr_indx)

5

In [24]:
sr_indx[sr_indx>2]

2    3
3    4
4    5
dtype: int64

In [25]:
sr_1 = pd.Series([1,2,3,4])
sr_2 = pd.Series([5,6,7,8])
print(sr_1)
print(sr_2)


sr_sum = sr_1 + sr_2
print(sr_sum) 


sr_3 = pd.Series([1,2,3])

sr_sum_unequ = sr_2 + sr_3
print(sr_sum_unequ)

0    1
1    2
2    3
3    4
dtype: int64
0    5
1    6
2    7
3    8
dtype: int64
0     6
1     8
2    10
3    12
dtype: int64
0     6.0
1     8.0
2    10.0
3     NaN
dtype: float64

# DataFrame

In [ ]:
#pandas DataFrame is two-dimensional, size-mutable, potentially hererogeneous tabular data structure with labeled axes(rows and columns)

In [26]:
emt_df = pd.DataFrame()
print(emt_df)

Empty DataFrame
Columns: []
Index: []

# list to DataFrame

In [27]:
lst = ['a','b','c']
print(lst)

['a', 'b', 'c']

In [28]:
df_1 = pd.DataFrame(lst)
df_1

   0
0  a
1  b
2  c

In [29]:
ls_of_ls = [[1,2,3],[1,23,45],[5,2,4]]
print(ls_of_ls)

[[1, 2, 3], [1, 23, 45], [5, 2, 4]]

In [30]:
df_2 = pd.DataFrame(ls_of_ls)
df_2

   0   1   2
0  1   2   3
1  1  23  45
2  5   2   4

# dict to dataframe

In [31]:
dict1 = {'ID' : [1,2,3,4]}
dict1

{'ID': [1, 2, 3, 4]}

In [32]:
df_dict1 = pd.DataFrame(dict1)

df_dict1

   ID
0   1
1   2
2   3
3   4

In [33]:
dict2 = {'ID' : [1,2,3,4],
        "name": ['raja', 'rani', 'varsova','rajkot']}
dict2

{'ID': [1, 2, 3, 4], 'name': ['raja', 'rani', 'varsova', 'rajkot']}

In [34]:
df_dict2 = pd.DataFrame(dict2)
df_dict2

   ID     name
0   1     raja
1   2     rani
2   3  varsova
3   4   rajkot

In [35]:
dict_1 = [{'a':1, 'b':2}, {'a':3, 'b':4}]
dict_1

[{'a': 1, 'b': 2}, {'a': 3, 'b': 4}]

In [36]:
df_dict_1 = pd.DataFrame(dict_1)
df_dict_1

   a  b
0  1  2
1  3  4

In [37]:
dict_2 = [{'a':1, 'b':2}, {'a':3, 'b':4, 'c': 44}]
dict_2

[{'a': 1, 'b': 2}, {'a': 3, 'b': 4, 'c': 44}]

In [38]:
df_dict_2 = pd.DataFrame(dict_2)
df_dict_2

   a  b     c
0  1  2   NaN
1  3  4  44.0

# data importing/ reading

In [39]:
pd.read_csv("E:\Data set\Pandas_dataset_prac\student_results.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Data set\\Pandas_dataset_prac\\student_results.csv'

In [ ]:
import os
print(os.getcwd())

In [ ]:
df = pd.read_csv(r"E:\\Data set\\Pandas_dataset_prac\\Fortune_10.csv")
df

In [40]:
type(df)

pandas.core.frame.DataFrame

In [41]:
df.columns

Index(['ID', 'Name', 'Industry', 'Inception', 'Revenue', 'Expenses', 'Profit',
       'Growth'],
      dtype='object')

In [42]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", nrows = 1)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%

In [43]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", nrows = 3)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%

In [44]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", usecols = [1])
df

              Name
0          Lamtone
1        Stripfind
2  Canecorporation
3         Mattouch
4        Techdrill
5         Techline
6          Cityace
7   Kayelectronics
8          Ganzlax
9      Trantraxlax

In [45]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", usecols = [1,3,5])
df

              Name  Inception           Expenses
0          Lamtone       2009  6,482,465 Dollars
1        Stripfind       2010    916,455 Dollars
2  Canecorporation       2012  7,591,189 Dollars
3         Mattouch       2013  7,429,377 Dollars
4        Techdrill       2009  7,435,363 Dollars
5         Techline       2006  5,470,303 Dollars
6          Cityace       2010  6,249,498 Dollars
7   Kayelectronics       2009  3,878,113 Dollars
8          Ganzlax       2011                NaN
9      Trantraxlax       2011  5,635,276 Dollars

In [46]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", usecols = [1,4])
df

              Name       Revenue
0          Lamtone  $11,757,018
1        Stripfind  $12,329,371
2  Canecorporation  $10,597,009
3         Mattouch  $14,026,934
4        Techdrill  $10,573,990
5         Techline  $13,898,119
6          Cityace   $9,254,614
7   Kayelectronics   $9,451,943
8          Ganzlax  $14,001,180
9      Trantraxlax  $11,088,336

In [47]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", skiprows = 1)
df

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [48]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", skiprows = [1,3,4])
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
2,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
3,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
4,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
5,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
6,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [49]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", index_col = 'ID')
df

,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [50]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", index_col = 'Name')
df

,ID,Industry,Inception,Revenue,Expenses,Profit,Growth
Name,,,,,,,
Lamtone,1,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
Stripfind,2,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
Canecorporation,3,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
Mattouch,4,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
Techdrill,5,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
Techline,6,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
Cityace,7,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
Kayelectronics,8,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
Ganzlax,9,IT Services,2011,"$14,001,180",NaN,11901180,18%
Trantraxlax,10,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [51]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", index_col = 3)
df

,ID,Name,Industry,Revenue,Expenses,Profit,Growth
Inception,,,,,,,
2009,1,Lamtone,IT Services,"$11,757,018","6,482,465 Dollars",5274553,30%
2010,2,Stripfind,Financial Services,"$12,329,371","916,455 Dollars",11412916,20%
2012,3,Canecorporation,Health,"$10,597,009","7,591,189 Dollars",3005820,7%
2013,4,Mattouch,IT Services,"$14,026,934","7,429,377 Dollars",6597557,26%
2009,5,Techdrill,Health,"$10,573,990","7,435,363 Dollars",3138627,8%
2006,6,Techline,Health,"$13,898,119","5,470,303 Dollars",8427816,23%
2010,7,Cityace,Health,"$9,254,614","6,249,498 Dollars",3005116,6%
2009,8,Kayelectronics,Health,"$9,451,943","3,878,113 Dollars",5573830,4%
2011,9,Ganzlax,IT Services,"$14,001,180",NaN,11901180,18%
2011,10,Trantraxlax,Government Services,"$11,088,336","5,635,276 Dollars",5453060,7%

# header

In [52]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", header = 1)
df

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [53]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", header = None)
df

,0,1,2,3,4,5,6,7
0,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
1,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [54]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", names = ['A','B'])
df

,,,,,,A,B
ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", dtype = {'ID': 'float64', 'profit' : 'float64'})
df

# NAN values:

#N/A, #N/A N/A, #NA, -1.#QNAN, -1.#IND, NaN, nan, NA, NULL , null, n/a, nan, 1.#IND, 1.#QNAN

In [55]:
### na_values

In [56]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10 - Copy.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [57]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10 - Copy.csv", na_values = 'not available')
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,NaN
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [60]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10 - Copy.csv", na_values = 'not available')
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,NaN
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [59]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10 - Copy.csv", na_values =

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,NaN,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [61]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10 - Copy.csv", keep_default_na = True)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
#boost for perfomance if no null values 
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv", na_filter = False)
df

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()

In [ ]:
df.isnull().sum().sum()

In [ ]:
df.notnull()

In [ ]:
df.notnull().sum()

In [ ]:
df.notnull().sum().sum()

In [ ]:
import numpy as np
ser = pd.Series([1,2,3,np.nan, 4,np.nan])
ser

In [ ]:
ser.isnull()

In [ ]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_5 nan values.csv")
df

In [ ]:
df.dropna()

In [ ]:
df.dropna(axis = 1)

In [ ]:
df.dropna(axis = 0)

In [ ]:
#any - work like dropna

df.dropna(how = 'any')

In [ ]:
df.dropna(axis = 1,how = 'any')

In [ ]:
#all num row and values
df.dropna(how = 'all')

In [ ]:
df.dropna(thresh = 2)

In [ ]:
df.dropna(thresh = )

In [ ]:
df

In [ ]:
df.dropna(thresh = 0)

In [ ]:
df.dropna(thresh = 2)

In [ ]:
df.dropna(subset = ['Profit'])

In [ ]:
df.fillna({'Expenses': 'none', 'Profit':55})

In [ ]:
df.fillna(method = 'ffill')

In [ ]:
df.fillna(method = 'pad') #same as ffill

In [ ]:
df.fillna(method = 'bfill')

In [ ]:
# row fillingA

df.fillna(method = 'ffill', axis = 0)

In [ ]:
# colums axis = 1


df.fillna(method = 'ffill', axis = 1)

In [ ]:
df.fillna(55, limit = 1) # columns vise / limit only use with method

In [ ]:
df.fillna(method = 'ffill' , limit = 2, axis = 0)

In [ ]:
df.fillna(method = 'ffill' , limit = 2, axis = 1)

# replace()
to_replace , limit, value, regex, inplace, method

In [ ]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\Fortune_10.csv")
df

In [ ]:
df.replace(to_replace = 'Health', value = 'it serv')

In [ ]:
df.replace('IT Services', 'AI/ML')

In [ ]:
df.replace(10,15)

In [ ]:
df.replace({'Industry' : 'Health'}, 'nan')

In [ ]:
df.replace('[A-Za-z]', 0) #when used regex it will work

In [ ]:
# regex = Regular expression

In [ ]:
df.replace('[A-Za-z]', 0, regex = True)

In [ ]:
df.replace({'Industry' : '[A-Za-z]'}, 0 , regex = True)

In [ ]:
df.replace('Financial Services' , method = 'ffill')

# interpolate() function :
pandas interploat() function is basically used to fill Nan values in dataframe or series

> DataFrame.interpolate()
> Series.interpolate()


parameters : method axis , limit, inplace, limit_direction , limit_area

In [166]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\student_results - copy.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.0,2.0,9.0,3.0,5,50.0
1,1002,10.0,6.0,8.0,2.0,0,80.0
2,1003,10.0,NaN,NaN,2.0,4,60.0
3,1004,11.0,NaN,NaN,1.0,5,45.0
4,1005,11.0,NaN,NaN,2.0,0,NaN
5,1006,11.0,10.0,7.0,0.0,0,NaN
6,1007,NaN,4.0,6.0,0.0,0,NaN
7,1008,NaN,10.0,NaN,NaN,0,90.0
8,1009,12.0,2.0,8.0,2.0,4,60.0
9,1010,12.0,6.0,9.0,1.0,0,85.0

In [168]:
# fill only numeric values not char

df.interpolate()

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.000000,2.0,9.00,3.0,5,50.00
1,1002,10.000000,6.0,8.00,2.0,0,80.00
2,1003,10.000000,7.0,7.75,2.0,4,60.00
3,1004,11.000000,8.0,7.50,1.0,5,45.00
4,1005,11.000000,9.0,7.25,2.0,0,56.25
5,1006,11.000000,10.0,7.00,0.0,0,67.50
6,1007,11.333333,4.0,6.00,0.0,0,78.75
7,1008,11.666667,10.0,7.00,1.0,0,90.00
8,1009,12.000000,2.0,8.00,2.0,4,60.00
9,1010,12.000000,6.0,9.00,1.0,0,85.00

In [170]:
df.interpolate(method = 'linear')

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.000000,2.0,9.00,3.0,5,50.00
1,1002,10.000000,6.0,8.00,2.0,0,80.00
2,1003,10.000000,7.0,7.75,2.0,4,60.00
3,1004,11.000000,8.0,7.50,1.0,5,45.00
4,1005,11.000000,9.0,7.25,2.0,0,56.25
5,1006,11.000000,10.0,7.00,0.0,0,67.50
6,1007,11.333333,4.0,6.00,0.0,0,78.75
7,1008,11.666667,10.0,7.00,1.0,0,90.00
8,1009,12.000000,2.0,8.00,2.0,4,60.00
9,1010,12.000000,6.0,9.00,1.0,0,85.00

In [4]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\student_results - copy.csv", parse_dates = ['Study hrs'], index_col = 'Class')
df

C:\Users\lenovo\AppData\Local\Temp\ipykernel_7136\1411896495.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("E:\Data set\Pandas_dataset_prac\student_results - copy.csv", parse_dates = ['Study hrs'], index_col = 'Class')

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10.0,1001,2,9.0,3.0,5,50.0
10.0,1002,6,8.0,2.0,0,80.0
10.0,1003,NaN,NaN,2.0,4,60.0
11.0,1004,NaN,NaN,1.0,5,45.0
11.0,1005,NaN,NaN,2.0,0,NaN
11.0,1006,10,7.0,0.0,0,NaN
NaN,1007,4,6.0,0.0,0,NaN
NaN,1008,10,NaN,NaN,0,90.0
12.0,1009,2,8.0,2.0,4,60.0
12.0,1010,6,9.0,1.0,0,85.0

In [177]:
# df.interpolate(method = 'nearest')

# loc and iloc

Access a group of rows & columns by label(s) or boolean array.

In [178]:
import pandas as pd

In [179]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\student_results.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [6]:
df.loc[:]

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10.0,1001,2,9.0,3.0,5,50.0
10.0,1002,6,8.0,2.0,0,80.0
10.0,1003,NaN,NaN,2.0,4,60.0
11.0,1004,NaN,NaN,1.0,5,45.0
11.0,1005,NaN,NaN,2.0,0,NaN
11.0,1006,10,7.0,0.0,0,NaN
NaN,1007,4,6.0,0.0,0,NaN
NaN,1008,10,NaN,NaN,0,90.0
12.0,1009,2,8.0,2.0,4,60.0
12.0,1010,6,9.0,1.0,0,85.0

In [181]:
df.loc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [182]:
df.loc[1]

Student ID                1002
Class                       10
Study hrs                    6
Sleeping hrs                 8
Social Media usage hrs       2
Mobile Games hrs             0
Percantege                  80
Name: 1, dtype: int64

In [183]:
df.loc[[0,1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80

In [185]:
df.loc[[2,4]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
2,1003,10,3,8,2,4,60
4,1005,11,4,7,2,0,75

In [188]:
df.loc[4, 'Class']

np.int64(11)

In [189]:
df.loc[0:3, 'Class']

0    10
1    10
2    10
3    11
Name: Class, dtype: int64

In [191]:
df.loc[0:2, 'Percantege']

0    50
1    80
2    60
Name: Percantege, dtype: int64

In [7]:
df

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10.0,1001,2,9.0,3.0,5,50.0
10.0,1002,6,8.0,2.0,0,80.0
10.0,1003,NaN,NaN,2.0,4,60.0
11.0,1004,NaN,NaN,1.0,5,45.0
11.0,1005,NaN,NaN,2.0,0,NaN
11.0,1006,10,7.0,0.0,0,NaN
NaN,1007,4,6.0,0.0,0,NaN
NaN,1008,10,NaN,NaN,0,90.0
12.0,1009,2,8.0,2.0,4,60.0
12.0,1010,6,9.0,1.0,0,85.0

In [194]:
df.loc[df['Class'] <11]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60

In [197]:
df.loc[df['Class'] <11, ['Percantege']]

   Percantege
0          50
1          80
2          60

In [198]:
# integer location based indexing

In [199]:
df.iloc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [200]:
 df.iloc[[0]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50

In [8]:
df

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10.0,1001,2,9.0,3.0,5,50.0
10.0,1002,6,8.0,2.0,0,80.0
10.0,1003,NaN,NaN,2.0,4,60.0
11.0,1004,NaN,NaN,1.0,5,45.0
11.0,1005,NaN,NaN,2.0,0,NaN
11.0,1006,10,7.0,0.0,0,NaN
NaN,1007,4,6.0,0.0,0,NaN
NaN,1008,10,NaN,NaN,0,90.0
12.0,1009,2,8.0,2.0,4,60.0
12.0,1010,6,9.0,1.0,0,85.0

In [202]:
df.iloc[:,0]

0    1001
1    1002
2    1003
3    1004
4    1005
5    1006
6    1007
7    1008
8    1009
9    1010
Name: Student ID, dtype: int64

In [203]:
df.iloc[[0,1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80

# groupby 

pandas groupby function is used ot split the data into groups based on some creiteria

- splitting the object
- applying the function
- combining the result

In [206]:
df = pd.read_csv("E:\Data set\Pandas_dataset_prac\student_results GROUP BY.csv")
df

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

In [207]:
gr1 = df.groupby(by = 'Section')
gr1

In [208]:
gr1.groups

{'A': [0, 2], 'B': [1], 'C': [3, 4]}

In [210]:
df.groupby(['Section', 'Class']).groups

{('A', 10): [0, 2], ('B', 10): [1], ('C', 11): [3], ('C', 12): [4]}

In [211]:
for Section, df_1 in gr1:
    print(Section)
    print(df_1)

A
   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
0        1001       A     10          2                       3          50
2        1003       A     10          3                       2          60
B
   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
1        1002       B     10          6                       2          80
C
   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

In [212]:
list(gr1)

[('A',
     Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
  0        1001       A     10          2                       3          50
  2        1003       A     10          3                       2          60),
 ('B',
     Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
  1        1002       B     10          6                       2          80),
 ('C',
     Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
  3        1004       C     11          0                       1          45
  4        1005       C     12          5                       2          75)]

In [213]:
dict(list(gr1))

{'A':    Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
 0        1001       A     10          2                       3          50
 2        1003       A     10          3                       2          60,
 'B':    Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
 1        1002       B     10          6                       2          80,
 'C':    Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
 3        1004       C     11          0                       1          45
 4        1005       C     12          5                       2          75}

In [215]:
df.groupby('Class').get_group(10)

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60

In [217]:
df.groupby('Section').get_group('A')

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percantege
0        1001       A     10          2                       3          50
2        1003       A     10          3                       2          60

In [218]:
gr1.sum()

         Student ID  Class  Study hrs  Social Media usage hrs  Percantege
Section
A              2004     20          5                       5         110
B              1002     10          6                       2          80
C              2009     23          5                       3         120

In [219]:
gr1.mean()

         Student ID  Class  Study hrs  Social Media usage hrs  Percantege
Section
A            1002.0   10.0        2.5                     2.5        55.0
B            1002.0   10.0        6.0                     2.0        80.0
C            1004.5   11.5        2.5                     1.5        60.0

In [220]:
gr1.describe()

        Student ID                                                      \
             count    mean       std     min      25%     50%      75%
Section
A              2.0  1002.0  1.414214  1001.0  1001.50  1002.0  1002.50
B              1.0  1002.0       NaN  1002.0  1002.00  1002.0  1002.00
C              2.0  1004.5  0.707107  1004.0  1004.25  1004.5  1004.75

                Class        ... Social Media usage hrs      Percantege        \
            max count  mean  ...                    75%  max      count  mean
Section                      ...
A        1003.0   2.0  10.0  ...                   2.75  3.0        2.0  55.0
B        1002.0   1.0  10.0  ...                   2.00  2.0        1.0  80.0
C        1005.0   2.0  11.5  ...                   1.75  2.0        2.0  60.0


               std   min   25%   50%   75%   max
Section
A         7.071068  50.0  52.5  55.0  57.5  60.0
B              NaN  80.0  80.0  80.0  80.0  80.0
C        21.213203  45.0  52.5  60.0  67.5  75.0

[3 rows x 40 columns]

In [221]:
gr1.agg(['sum', 'max', 'mean'])

        Student ID               Class           Study hrs           \
               sum   max    mean   sum max  mean       sum max mean
Section
A             2004  1003  1002.0    20  10  10.0         5   3  2.5
B             1002  1002  1002.0    10  10  10.0         6   6  6.0
C             2009  1005  1004.5    23  12  11.5         5   5  2.5

        Social Media usage hrs          Percantege
                           sum max mean        sum max  mean
Section
A                            5   3  2.5        110  60  55.0
B                            2   2  2.0         80  80  80.0
C                            3   2  1.5        120  75  60.0

# Merg

In [222]:
df1 = pd.DataFrame({ 'ID' : [1,2,34,4],
                     'Class' : [5,6,7,8]})
df1

   ID  Class
0   1      5
1   2      6
2  34      7
3   4      8

In [223]:
df2 = pd.DataFrame({ 'ID' : [1,2,3,4],
                     "Name" : ['A','B','C','D']})
df2

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

In [224]:
pd.merge(df1,df2)

   ID  Class Name
0   1      5    A
1   2      6    B
2   4      8    D

In [225]:
pd.merge(df1,df2, on = "ID")

   ID  Class Name
0   1      5    A
1   2      6    B
2   4      8    D

In [226]:
pd.merge(df2,df1, on = "ID")

   ID Name  Class
0   1    A      5
1   2    B      6
2   4    D      8

In [227]:
# intersection = inner , same as merge on id(same valuse merge different value not)
pd.merge(df1,df2, on = 'ID' , how = 'inner')

   ID  Class Name
0   1      5    A
1   2      6    B
2   4      8    D

In [228]:
pd.merge(df1,df2, on = 'ID', how = 'left')

   ID  Class Name
0   1      5    A
1   2      6    B
2  34      7  NaN
3   4      8    D

In [229]:
pd.merge(df1,df2, on = 'ID', how = 'right')

   ID  Class Name
0   1    5.0    A
1   2    6.0    B
2   3    NaN    C
3   4    8.0    D

In [230]:
pd.merge(df1,df2, on = 'ID', how = 'outer')

   ID  Class Name
0   1    5.0    A
1   2    6.0    B
2   3    NaN    C
3   4    8.0    D
4  34    7.0  NaN

In [231]:
pd.merge(df1,df2, on = 'ID', how = 'outer' , indicator  = True)

   ID  Class Name      _merge
0   1    5.0    A        both
1   2    6.0    B        both
2   3    NaN    C  right_only
3   4    8.0    D        both
4  34    7.0  NaN   left_only

In [232]:
pd.merge(df1,df2, left_index = True, right_index = True)

   ID_x  Class  ID_y Name
0     1      5     1    A
1     2      6     2    B
2    34      7     3    C
3     4      8     4    D

In [233]:
pd.merge(df1,df2, on = 'ID', suffixes = ('_Higher', '_Middle')) # to show get same columns try on class

   ID  Class Name
0   1      5    A
1   2      6    B
2   4      8    D

# Concat()

padas provides various facilities for easily combining together Series, DataFrame and panel objects

In [234]:
sr1 = pd.Series([0,1,2])
sr1

0    0
1    1
2    2
dtype: int64

In [235]:
sr2 = pd.Series([3,4,5])

In [237]:
pd.concat([sr1,sr2])

0    0
1    1
2    2
0    3
1    4
2    5
dtype: int64

In [238]:
sr3 = pd.Series([3,4,5,43,3])

In [239]:
pd.concat([sr1,sr3])

0     0
1     1
2     2
0     3
1     4
2     5
3    43
4     3
dtype: int64

In [240]:
df1 = pd.DataFrame({ "ID" : [1,2,3,4],
                     'Name' : ['A','B','C','D'],
                     'Class' : [5,4,3,5]})
df1

   ID Name  Class
0   1    A      5
1   2    B      4
2   3    C      3
3   4    D      5

In [241]:
df2 = pd.DataFrame({ "ID" : [5,6,7,8],
                     'Name' : ['E','F','G','H'],
                     'Class' : [9,10,11,12]})
df2

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [242]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      4
2   3    C      3
3   4    D      5
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [243]:
pd.concat([df1,df2], axis = 1)

   ID Name  Class  ID Name  Class
0   1    A      5   5    E      9
1   2    B      4   6    F     10
2   3    C      3   7    G     11
3   4    D      5   8    H     12

In [244]:
pd.concat([df2,df1], axis = 0)

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12
0   1    A      5
1   2    B      4
2   3    C      3
3   4    D      5

In [245]:
pd.concat([df1,df2], axis = 0, ignore_index = True)

   ID Name  Class
0   1    A      5
1   2    B      4
2   3    C      3
3   4    D      5
4   5    E      9
5   6    F     10
6   7    G     11
7   8    H     12

In [247]:
pd.concat([df1,df2], keys = ['df1','df2'])

       ID Name  Class
df1 0   1    A      5
    1   2    B      4
    2   3    C      3
    3   4    D      5
df2 0   5    E      9
    1   6    F     10
    2   7    G     11
    3   8    H     12

In [246]:
# try with unmatch dataframe

# join

DataFrame join is a convenient method for combining the columns of two potentially differently - indexed.

In [249]:
df1 = pd.DataFrame({ 'a' : [1,2,30],
                     'b' : [11.2,12.44,30]})

df1 = pd.DataFrame({ 'c' : [4,5,6],
                     'd' : [10,20.44,60]})

display(df1,df2)

   c      d
0  4  10.00
1  5  20.44
2  6  60.00

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [250]:
df1.join(df2)

   c      d  ID Name  Class
0  4  10.00   5    E      9
1  5  20.44   6    F     10
2  6  60.00   7    G     11

In [251]:
df2.join(df1)

   ID Name  Class    c      d
0   5    E      9  4.0  10.00
1   6    F     10  5.0  20.44
2   7    G     11  6.0  60.00
3   8    H     12  NaN    NaN

In [252]:
# try with uneven dataframe

In [253]:
# how = inner, how = 'outer

In [254]:
#rsuffix = '1'

# append

pandas append funcion is used to append rows of other dataframe to the end of the given dataframe, returning a new datafarme object

In [ ]:
df1 = pd.DataFrame({ 'a' : [1,2,30],
                     'b' : [11.2,12.44,30]})

df1 = pd.DataFrame({ 'c' : [4,5,6],
                     'd' : [10,20.44,60]})

In [255]:
df1.append(df2)

AttributeError: 'DataFrame' object has no attribute 'append'